### ISSUE TITLE
[SW] Calibres - Protocolo (con calibre)

### ISSUE THREAD

**Issue by jmestanza** [mregueira/DisenioBJAM#12]
Probar el software implementado en #3 pero teniendo los calibres digitales obtenidos en #13

**Comment by mregueira** [comment]
Probamos eso y funciono todo ok, el pinout estaba ok tambien. Falta generalizar para los otros calibres. Recordar REQ va en estado Output Open Drain. Commit https://github.com/mregueira/DisenioBJAM/commit/53f93810cc698f4f71ef4fe85873198e9d5c0fcc

**Comment by jmestanza** [comment]
https://github.com/mregueira/DisenioBJAM/commit/53f93810cc698f4f71ef4fe85873198e9d5c0fcc
