### ISSUE TITLE
[HW] Cambios a la nueva placa

### ISSUE THREAD

**Issue by amartorell** [mregueira/DisenioBJAM#22]
Cambiar:
 - [x] Patitas de fuente 5V y 24V
 - [x] Conector ethernet
 - [x] Agregar testpoint para tensiones
 - [x] Footprint del MUR410
 - [x] Resistencia de pull down a las salidas de control digital (ahora que sabemos que anda no hace falta)
 - [x] Resistencias pull up ethernet PHY
 - [x] Resistencia de pull down a pedal y PLC
 - [x] Puentear masas del integrado ADS7841
 - [x] Averiguar con las aplication note como hacer el ruteo de las pistas de ethernet para que tome 100Mbps
 - [x] Revisar footprint de los SMD

**Comment by mregueira** [comment]
La posta para 100Mbps seria control de impedancia, aparte del ruteo diferencial. Pero para eso la placa tiene que ser de al menos 4 capas y el costo se eleva mucho.
