### ISSUE TITLE
[SW] Calibres - Protocolo (con analog)

### ISSUE THREAD

**Issue by mregueira** [mregueira/DisenioBJAM#3]
Hay que hacer el protocolo de los calibres. Había lo que encontramos para arduino que hay que traducir a C.

**Comment by jmestanza** [comment]
Para esta parte con el analog en la parte de Patterns se puede fakear el Calibre y se puede probar el codigo. Para esta parte necesitariamos un CLK, DATA y REQ (lo generamos todo con eso). 
En el caso de verdad, REQ es una entrada del calibre.
En este caso, el REQ actua como una senial de sincronismo para el micro --> en el caso de verdad esto cambia.

**Comment by jmestanza** [comment]
Probado, funciona. Ahora queda probar con los calibres y la placa de prueba
