### ISSUE TITLE
[DOC] Cosas que faltan del informe

### ISSUE THREAD

**Issue by mregueira** [mregueira/DisenioBJAM#30]
Cosas que quedan poner en el informe:
- [x] #34
- [x] Agregar foto del pedal (la tengo yo)

--------------------------------------------------------------------------------------------------
Revisión Joaco
**Cosas generales:**
- [x] Pagina 10 - Acronimos - TBD y TBC deberian estar como AC y DC (para ser consistentes)
- [x] Pagina 11 - Resumen - https://puu.sh/IFWHT/a3ad16f952.png, no deberian ser **salidas digitales**?
- [x] Pagina 18 - INT-COM-05 - No pieza presente -> valor nulo -> no tiene sentido, el calibre me responde con lo que mide
- [x] Pagina 24 - Especificaciones de tests - https://puu.sh/IFXzY/a972e60481.png,  13 datos -> son 13 frames de 4 bit cada uno, o sea que son 13 * 4 = 52 bits en total... no tiene mucho sentido querer ver los 52 bits en el osciloscopio (la cuenta  que originalmente hicimos era 13bits * (1/4096) = 3.17ms, por eso pusimos 5ms)
- [x] Pagina 25 - T-PERF05 - "3.	Verificar que se visualiza en ella que la batería se carga en tiempo y forma acordes." --> hicimos mencion de cuanto es "tiempo acorde"?
- [x] Pagina 26 - "REQ-05 Pieza no presente, transmitir valor nulo de medición." lo mismo que en pagina 18 INT-COM-05. REQ -06, lo mismo que pagina 18 INT-COM-06
- [x] Pagina 52 - hay un highlight amarillo, es a proposito? creo que no va
**Software:**
- [x] Pagina 59 - Descripcion de subrutinas - Esto seguramente tenga que ser modificado ya que no se llaman asi las funciones y ahora tenemos las funciones posta para saber que utilizan
- [x] Pagina 60 - Plan de pruebas y de depuracion de software. Cambiaron los nombres y creo que se puede redactar mejor

**Comment by jmestanza** [comment]
Pase las tareas no resueltas al issue #36
